name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-gitx:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ M1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Python install
        run: brew install python@3.8
      - name: Python3 version
        run: python3 --version
      - name: Install requirements
        run: |
          rm -rf venv/
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Check tensorflow
        run: |
          source venv/bin/activate
          python3 -c 'import tensorflow as tf; print("tensorflow=", tf.__version__)'
          python3 ./playground/numpyTest.py
          python3 ./playground/testInstallation.py
      - name: Speed test
        run: |
          source venv/bin/activate
          python3 ./playground/speedTest.py

      - name: Prepare changes
        run: |
          git commit --dry-run && echo "Things to commit" || echo "Clean repo, nothing to archive"
          if git commit --dry-run; then
            mkdir ./modified-files
            git ls-files -o --exclude-standard | while read filename
            do
                echo "Printing: $filename"
                cp "$filename" ./modified-files
            done
            git ls-files --modified | while read filename
            do
                echo "Printing: $filename"
                cp "$filename" ./modified-files
            done
          else
            echo "Clean repo"
          fi
      - name: Archive changes
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: changed
          path: ./modified-files
