name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-gitx:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ M1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Python install
        run: brew install python@3.8
      - name: Python3 version
        run: python3 --version
      - name: prepare
        run: |
          pip3 install --upgrade pip
          python3 --version
          pip3 install -r requirements.txt
      - name: check tensorflow
        run: |
          python3 -c 'import tensorflow as tf; print(tf.__version__)'
      - name: speed test
        run: |
          python3 ./playground/speedTest.py
