name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-gitx:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ JetsonNano ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Python version
        run: python --version
      - name: prepare
        run: python -m pip install --upgrade pip
      - name: check tensorflow
        run: python -c 'import tensorflow as tf; print(tf.__version__)'
      - name: speed test
        run: |
          python ./playground/speedTest.py
